=== claudianistal/F1Desktop/xml/circuito.dtd
<!ELEMENT evento (circuito, carrera, bibliografia, fotografias, videos, coordenadaMeta, puntosCircuito)>
<!ELEMENT circuito (nombre, longitudCir, anchuraMedia, localidad, pais)>
<!ELEMENT carrera (fecha, hora, nVueltas)>
<!ELEMENT bibliografia (referencia+)>
<!ELEMENT fotografias (foto+)>
<!ELEMENT videos (video*)>
<!ELEMENT coordenadaMeta (longitudCoord, latitudCoord, altitudCoord)>
<!ELEMENT puntosCircuito (tramo+)>


<!ELEMENT nombre (#PCDATA)>
<!ELEMENT longitudCir (#PCDATA)>
<!ELEMENT anchuraMedia (#PCDATA)>
<!ELEMENT localidad (#PCDATA)>
<!ELEMENT pais (#PCDATA)>
<!ELEMENT fecha (#PCDATA)>
<!ELEMENT hora (#PCDATA)>
<!ELEMENT nVueltas (#PCDATA)>
<!ELEMENT referencia (#PCDATA)>
<!ELEMENT foto (#PCDATA)>
<!ELEMENT video (#PCDATA)>
<!ELEMENT longitudCoord (#PCDATA)>
<!ELEMENT latitudCoord (#PCDATA)>
<!ELEMENT altitudCoord (#PCDATA)>

<!ELEMENT coordenadaInicio (latitud, longitud, altura)>
<!ELEMENT coordenadaFinal (latitud, longitud, altura)>
<!ELEMENT latitud (#PCDATA)>
<!ELEMENT longitud (#PCDATA)>
<!ELEMENT altura (#PCDATA)>
<!ELEMENT tramo (coordenadaInicio, coordenadaFinal)>
<!ATTLIST tramo sector CDATA #REQUIRED>
<!ATTLIST tramo distancia CDATA #REQUIRED>
<!ATTLIST tramo unidades CDATA #REQUIRED>

=== claudianistal/F1Desktop/xml/circuito.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE evento SYSTEM "circuito.dtd">

<evento>
    <circuito>
        <nombre>Hungaroring</nombre>
        <longitudCir>4381km</longitudCir>
        <anchuraMedia>10m</anchuraMedia>
        <localidad>Mogyoród</localidad>
        <pais>Hungría</pais>
    </circuito>
    <carrera>
        <fecha>21 de Julio de 2024</fecha>
        <hora>15:00</hora>
        <nVueltas>70</nVueltas>
    </carrera>
    <bibliografia>
        <referencia>1. Web Oficial de la carrera: https://www.formula1.com/en/racing/2024/hungary/circuit</referencia>
        <referencia>2. Acerca del circuito: https://www.dazn.com/es-ES/news/motor/circuito-hungaroring-donde-esta-como-es-caracteristicas-como-llegar-fotos-escenario-gp-hungria-mundial-f1/dhwmzbcpsnvf1q3erxggjo5op</referencia>
        <referencia>3. Web Oficial del circuito: https://hungaroring.hu/site/</referencia>
    </bibliografia>
    <fotografias>
        <foto>mapaCircuito.jpg</foto>
        <foto>hungaroring.jpg</foto>
        <foto>gradasCircuito.jpg</foto>
    </fotografias>
    <videos>
        <video></video>
    </videos>
    <coordenadaMeta>
        <longitudCoord>47°34'43"N</longitudCoord>
        <latitudCoord>19°14'56"E</latitudCoord>
        <altitudCoord>236</altitudCoord>
    </coordenadaMeta>
    <puntosCircuito>
        <tramo sector="1" distancia="628,49" unidades="m">
            <coordenadaInicio>
                <latitud>47°34'43"N</latitud>
                <longitud>19°14'56"E</longitud>
                <altura>236</altura>
            </coordenadaInicio>
            <coordenadaFinal>
                <latitud>47°34'55"N</latitud>
                <longitud>19°14'56"E</longitud>
                <altura>236</altura>
            </coordenadaFinal>
        </tramo>
        <tramo sector="1" distancia="22,4" unidades="m">
            <coordenadaInicio>
                <latitud>47°34'43"N</latitud>
                <longitud>19°14'56"E</longitud>
                <altura>236</altura>
            </coordenadaInicio>
            <coordenadaFinal>
                <latitud>47°34'56"N</latitud>
                <longitud>19°14'32"E</longitud>
                <altura>228</altura>
            </coordenadaFinal>
        </tramo>
        <tramo sector="1" distancia="22,78" unidades="m">
            <coordenadaInicio>
                <latitud>47°34'56"N</latitud>
                <longitud>19°14'32"E</longitud>
                <altura>228</altura>
            </coordenadaInicio>
            <coordenadaFinal>
                <latitud>47°34'57"N</latitud>
                <longitud>19°14'33"E</longitud>
                <altura>227</altura>
            </coordenadaFinal>
        </tramo>
        <tramo sector="1" distancia="91,9" unidades="m">
            <coordenadaInicio>
                <latitud>47°34'57"N</latitud>
                <longitud>19°14'33"E</longitud>
                <altura>227</altura>
            </coordenadaInicio>
            <coordenadaFinal>
                <latitud>47°34'56"N</latitud>
                <longitud>19°14'37"E</longitud>
                <altura>225</altura>
            </coordenadaFinal>
        </tramo>
        <tramo sector="1" distancia="83,3" unidades="m">
            <coordenadaInicio>
                <latitud>47°34'56"N</latitud>
                <longitud>19°14'37"E</longitud>
                <altura>225</altura>
            </coordenadaInicio>
            <coordenadaFinal>
                <latitud>47°34'55"N</latitud>
                <longitud>19°14'42"E</longitud>
                <altura>224</altura>
            </coordenadaFinal>
        </tramo>
        <tramo sector="1" distancia="259,02" unidades="m">
            <coordenadaInicio>
                <latitud>47°34'55"N</latitud>
                <longitud>19°14'42"E</longitud>
                <altura>224</altura>
            </coordenadaInicio>
            <coordenadaFinal>
                <latitud>47°34'50"N</latitud>
                <longitud>19°14'51"E</longitud>
                <altura>221</altura>
            </coordenadaFinal>
        </tramo>
        <tramo sector="2" distancia="50,73" unidades="m">
            <coordenadaInicio>
                <latitud>47°34'50"N</latitud>
                <longitud>19°14'51"E</longitud>
                <altura>221</altura>
            </coordenadaInicio>
            <coordenadaFinal>
                <latitud>47°34'51"N</latitud>
                <longitud>19°14'53"E</longitud>
                <altura>218</altura>
            </coordenadaFinal>
        </tramo>
        <tramo sector="2" distancia="41,88" unidades="m">
            <coordenadaInicio>
                <latitud>47°34'51"N</latitud>
                <longitud>19°14'53"E</longitud>
                <altura>218</altura>
            </coordenadaInicio>
            <coordenadaFinal>
                <latitud>47°34'52"N</latitud>
                <longitud>19°14'54"E</longitud>
                <altura>215</altura>
            </coordenadaFinal>
        </tramo>
        <tramo sector="2" distancia="134,26" unidades="m">
            <coordenadaInicio>
                <latitud>47°34'52"N</latitud>
                <longitud>19°14'54"E</longitud>
                <altura>215</altura>
            </coordenadaInicio>
            <coordenadaFinal>
                <latitud>47°34'56"N</latitud>
                <longitud>19°14'51"E</longitud>
                <altura>206</altura>
            </coordenadaFinal>
        </tramo>
        <tramo sector="2" distancia="390,62" unidades="m">
            <coordenadaInicio>
                <latitud>47°34'56"N</latitud>
                <longitud>19°14'51"E</longitud>
                <altura>206</altura>
            </coordenadaInicio>
            <coordenadaFinal>
                <latitud>47°35'08"N</latitud>
                <longitud>19°14'59"E</longitud>
                <altura>209</altura>
            </coordenadaFinal>
        </tramo>
        <tramo sector="2" distancia="71,27" unidades="m">
            <coordenadaInicio>
                <latitud>47°35'08"N</latitud>
                <longitud>19°14'59"E</longitud>
                <altura>209</altura>
            </coordenadaInicio>
            <coordenadaFinal>
                <latitud>47°35'10"N</latitud>
                <longitud>19°15'02"E</longitud>
                <altura>214</altura>
            </coordenadaFinal>
        </tramo>
        <tramo sector="2" distancia="193,38" unidades="m">
            <coordenadaInicio>
                <latitud>47°35'10"N</latitud>
                <longitud>19°15'02"E</longitud>
                <altura>214</altura>
            </coordenadaInicio>
            <coordenadaFinal>
                <latitud>47°35'16"N</latitud>
                <longitud>19°14'59"E</longitud>
                <altura>215</altura>
            </coordenadaFinal>
        </tramo>
        <tramo sector="2" distancia="54,6" unidades="m">
            <coordenadaInicio>
                <latitud>47°35'16"N</latitud>
                <longitud>19°14'59"E</longitud>
                <altura>215</altura>
            </coordenadaInicio>
            <coordenadaFinal>
                <latitud>47°35'18"N</latitud>
                <longitud>19°15'01"E</longitud>
                <altura>217</altura>
            </coordenadaFinal>
        </tramo>
        <tramo sector="2" distancia="57,04" unidades="m">
            <coordenadaInicio>
                <latitud>47°35'18"N</latitud>
                <longitud>19°15'01"E</longitud>
                <altura>217</altura>
            </coordenadaInicio>
            <coordenadaFinal>
                <latitud>47°35'18"N</latitud>
                <longitud>19°15'04"E</longitud>
                <altura>221</altura>
            </coordenadaFinal>
        </tramo>
        <tramo sector="2" distancia="57,04" unidades="m">
            <coordenadaInicio>
                <latitud>47°35'18"N</latitud>
                <longitud>19°15'01"E</longitud>
                <altura>217</altura>
            </coordenadaInicio>
            <coordenadaFinal>
                <latitud>47°35'18"N</latitud>
                <longitud>19°15'04"E</longitud>
                <altura>221</altura>
            </coordenadaFinal>
        </tramo>
        <tramo sector="2" distancia="227,81" unidades="m">
            <coordenadaInicio>
                <latitud>47°35'18"N</latitud>
                <longitud>19°15'04"E</longitud>
                <altura>221</altura>
            </coordenadaInicio>
            <coordenadaFinal>
                <latitud>47°35'12"N</latitud>
                <longitud>19°15'12"E</longitud>
                <altura>226</altura>
            </coordenadaFinal>
        </tramo>
        <tramo sector="2" distancia="38,18" unidades="m">
            <coordenadaInicio>
                <latitud>47°35'12"N</latitud>
                <longitud>19°15'12"E</longitud>
                <altura>226</altura>
            </coordenadaInicio>
            <coordenadaFinal>
                <latitud>47°35'11"N</latitud>
                <longitud>19°15'11"E</longitud>
                <altura>226</altura>
            </coordenadaFinal>
        </tramo>
        <tramo sector="2" distancia="164,02" unidades="m">
            <coordenadaInicio>
                <latitud>47°35'11"N</latitud>
                <longitud>19°15'11"E</longitud>
                <altura>226</altura>
            </coordenadaInicio>
            <coordenadaFinal>
                <latitud>47°35'06"N</latitud>
                <longitud>19°15'13"E</longitud>
                <altura>228</altura>
            </coordenadaFinal>
        </tramo>
        <tramo sector="2" distancia="29,43" unidades="m">
            <coordenadaInicio>
